server:
  port: 8700
spring:
  application:
    name: cloud-config-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaoCaiAWen/cloud_F
          search-paths: cloudConfigFils/
          username: wangwenbo
          password: wangwenbo.521
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/



