server:
  port: 6001
spring:
  application:
    name: cloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/


