server:
  port: 7001
spring:
  application:
    name: cloud-producer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
