server:
  port: 6002
spring:
  application:
    name: cloud-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/



