server:
  port: 9411
spring:
  application:
    name: zipkin-server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
  #zipkin\u7684ui\u754C\u9762\u914D\u7F6E
management:
  metrics:
    web:
      server:
        auto-time-requests: false
